export { authReducer, authActions } from './model/slice/auth-slice'
export { sendSmsCode, verifyOtp } from './model/services/verification-by-phone'
export { AuthPage } from './ui/auth-page'
export { EAuthStep } from './model/types/types'
export type { IPhoneFormProps } from './model/types/types'
